package com.zsmall.dao;

import com.zsmall.dataobject.ItemDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ItemDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Thu Feb 27 17:46:33 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Thu Feb 27 17:46:33 GMT+08:00 2020
     */
    int insert(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Thu Feb 27 17:46:33 GMT+08:00 2020
     */
    int insertSelective(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Thu Feb 27 17:46:33 GMT+08:00 2020
     */

    ItemDO selectByPrimaryKey(Integer id);

    List<ItemDO> selectAllItems();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Thu Feb 27 17:46:33 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Thu Feb 27 17:46:33 GMT+08:00 2020
     */
    int updateByPrimaryKey(ItemDO record);

    int updateIsBoughtByPrimaryKey(Integer id);

    int updateSales(@Param("amount")Integer amount, @Param("id")Integer id);
}