package com.zsmall.dao;

import com.zsmall.dataobject.SysLogDO;

public interface SysLogDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_LOG
     *
     * @mbggenerated Sun Aug 16 23:12:38 CST 2020
     */
    int insert(SysLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_LOG
     *
     * @mbggenerated Sun Aug 16 23:12:38 CST 2020
     */
    int insertSelective(SysLogDO record);
}