package com.zsmall.dataobject;

public class ItemDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.id
     *
     * @mbggenerated Thu Feb 27 17:46:33 GMT+08:00 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.title
     *
     * @mbggenerated Thu Feb 27 17:46:33 GMT+08:00 2020
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.price
     *
     * @mbggenerated Thu Feb 27 17:46:33 GMT+08:00 2020
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.brief_description
     *
     * @mbggenerated Thu Feb 27 17:46:33 GMT+08:00 2020
     */
    private String briefDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.total_description
     *
     * @mbggenerated Thu Feb 27 17:46:33 GMT+08:00 2020
     */
    private String totalDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.sales
     *
     * @mbggenerated Thu Feb 27 17:46:33 GMT+08:00 2020
     */
    private Integer sales;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.img_url
     *
     * @mbggenerated Thu Feb 27 17:46:33 GMT+08:00 2020
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.is_bought
     *
     * @mbggenerated Thu Feb 27 17:46:33 GMT+08:00 2020
     */
    private Integer isBought;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.id
     *
     * @return the value of item.id
     *
     * @mbggenerated Thu Feb 27 17:46:33 GMT+08:00 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.id
     *
     * @param id the value for item.id
     *
     * @mbggenerated Thu Feb 27 17:46:33 GMT+08:00 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.title
     *
     * @return the value of item.title
     *
     * @mbggenerated Thu Feb 27 17:46:33 GMT+08:00 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.title
     *
     * @param title the value for item.title
     *
     * @mbggenerated Thu Feb 27 17:46:33 GMT+08:00 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.price
     *
     * @return the value of item.price
     *
     * @mbggenerated Thu Feb 27 17:46:33 GMT+08:00 2020
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.price
     *
     * @param price the value for item.price
     *
     * @mbggenerated Thu Feb 27 17:46:33 GMT+08:00 2020
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.brief_description
     *
     * @return the value of item.brief_description
     *
     * @mbggenerated Thu Feb 27 17:46:33 GMT+08:00 2020
     */
    public String getBriefDescription() {
        return briefDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.brief_description
     *
     * @param briefDescription the value for item.brief_description
     *
     * @mbggenerated Thu Feb 27 17:46:33 GMT+08:00 2020
     */
    public void setBriefDescription(String briefDescription) {
        this.briefDescription = briefDescription == null ? null : briefDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.total_description
     *
     * @return the value of item.total_description
     *
     * @mbggenerated Thu Feb 27 17:46:33 GMT+08:00 2020
     */
    public String getTotalDescription() {
        return totalDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.total_description
     *
     * @param totalDescription the value for item.total_description
     *
     * @mbggenerated Thu Feb 27 17:46:33 GMT+08:00 2020
     */
    public void setTotalDescription(String totalDescription) {
        this.totalDescription = totalDescription == null ? null : totalDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.sales
     *
     * @return the value of item.sales
     *
     * @mbggenerated Thu Feb 27 17:46:33 GMT+08:00 2020
     */
    public Integer getSales() {
        return sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.sales
     *
     * @param sales the value for item.sales
     *
     * @mbggenerated Thu Feb 27 17:46:33 GMT+08:00 2020
     */
    public void setSales(Integer sales) {
        this.sales = sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.img_url
     *
     * @return the value of item.img_url
     *
     * @mbggenerated Thu Feb 27 17:46:33 GMT+08:00 2020
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.img_url
     *
     * @param imgUrl the value for item.img_url
     *
     * @mbggenerated Thu Feb 27 17:46:33 GMT+08:00 2020
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.is_bought
     *
     * @return the value of item.is_bought
     *
     * @mbggenerated Thu Feb 27 17:46:33 GMT+08:00 2020
     */
    public Integer getIsBought() {
        return isBought;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.is_bought
     *
     * @param isBought the value for item.is_bought
     *
     * @mbggenerated Thu Feb 27 17:46:33 GMT+08:00 2020
     */
    public void setIsBought(Integer isBought) {
        this.isBought = isBought;
    }
}